title: SpaceWorks Guides
description: "Interactive guides for Spacecoin and AtomicDEX."
keywords: "guides, spacecoin guides, atomicDEX guides, spacecoin, space coin, spacecoin-qt, spacecoin-qt guides, wallet, staking, atomicDEX, mm2, atomicDEX Desktop"
github:
  is_project_page: false

url: "https://guides.spaceworks.co"
url-pretty: "guides.spaceworks.co"
plugins:
  - jekyll-sitemap
  - jekyll-titles-from-headings

title-img: "/images/logo.png"
navbar-links:
  Spacecoin: "https://spacecoin.network"
  AtomicDEX: "https://atomicdex.io"
  SpaceWorks:
    - Site: "https://spaceworks.co"
    - Explorer: "https://explorer.spaceworks.co"
    - Mining Pool: "https://mining.spaceworks.co"

social-network-links:
  email: "hello@spaceworks.co"
  github: SpaceWorksCo
  twitter: SpaceWorks__

exclude:
  - CHANGELOG.md
  - CNAME
  - GEMFILE
  - GEMFILE.lock
  - LICENSE

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
